name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Автоматичний деплой при пуші в main
  workflow_dispatch:  # Дозволяє вручну запускати workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Крок для аутентифікації в Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Налаштування Google Cloud SDK
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy app \
            --image us-docker.pkg.dev/dotted-music-435509-q2/app-repo/app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }}
