name: Deploy to Cloud Run

on:
  workflow_dispatch: # Дозволяє вручну запускати workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }} # Використовуємо секрет
          project_id: dotted-music-435509-q2
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy app \
            --image us-docker.pkg.dev/dotted-music-435509-q2/app-repo/app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
