name: Deploy to Cloud Run

on:
  workflow_run:
    workflows: ["Setup GCP Environment"]  # Ім'я першого воркфлоу
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to Cloud Run
      run: |
        echo "Deploying to Cloud Run..."
        gcloud run deploy your-service-name \
          --image gcr.io/${{ github.event.inputs.gcp_project_id }}/your-image-name:latest \
          --platform managed \
          --region us-central1 \
          --set-secrets GCP_SA_KEY=${{ github.event.inputs.environment_name }}/GCP_SA_KEY \
          --set-secrets GCP_PROJECT_ID=${{ github.event.inputs.environment_name }}/GCP_PROJECT_ID
