name: Setup GCP Environment

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Name of the environment (e.g., staging, production)'
        required: true
      gcp_project_id:
        description: 'GCP Project ID'
        required: true

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      run: |
        echo "Setting up Google Cloud SDK..."
        gcloud config set project ${{ github.event.inputs.gcp_project_id }}

    - name: Configure GitHub secrets and variables
      run: |
        echo "Setting up environment variables for ${{ github.event.inputs.environment_name }}..."
        echo "GCP_PROJECT_ID=${{ github.event.inputs.gcp_project_id }}" >> $GITHUB_ENV

    - name: Verify GCP setup
      run: |
        gcloud auth list
