name: Setup GCP Environment

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'Name of the environment (e.g., staging, production)'
        required: true
      gcp_project_id:
        description: 'GCP Project ID'
        required: true

permissions:
  contents: write
  deployments: write

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: sudo apt-get install gh -y

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      run: |
        echo "Setting up Google Cloud SDK..."
        gcloud config set project ${{ github.event.inputs.gcp_project_id }}

    - name: Create GitHub Environment
      run: |
        echo "Creating environment: ${{ github.event.inputs.environment_name }}"
        gh api repos/${{ github.repository }}/environments/${{ github.event.inputs.environment_name }} \
          --method PUT

      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Add secrets to GitHub Environment
      run: |
        echo "Adding secrets to the environment..."
        gh secret set GCP_SA_KEY --env ${{ github.event.inputs.environment_name }} --body "${{ secrets.GCP_SA_KEY }}"
        gh secret set GCP_PROJECT_ID --env ${{ github.event.inputs.environment_name }} --body "${{ github.event.inputs.gcp_project_id }}"
